Add analytics support for GoatCounter
cotes2020/jekyll-theme-chirpy pull request #1526
Opened 2024-02-05 09:28 UTC by smorkolama

## Type of change

- [ x] New feature (non-breaking change which adds functionality)

## Description
This PR adds support for a privacy-friendly alternative to Google Analytics called GoatCounter (https://www.goatcounter.com). The integration is relatively simple so it should be a low-risk addition. Documentation can be found here: https://www.goatcounter.com/help/start

Additionally I've tested this implementation in my own blog and it works fine. If you have any questions or remarks I will gladly address them of course.

2024-02-06 11:41 UTC, cotes2020 requested changes
It's a nice feature, thanks!

2024-02-06 11:41 UTC, cotes2020 commented on README.md
> +- GoatCounter
```suggestion
- Google Analytics / GoatCounter
```

2024-02-06 11:41 UTC, cotes2020 commented on _includes/goatcounter.html
> +<script data-goatcounter="https://{{ site.goatcounter.id }}.goatcounter.com/count"
Prettier format:

```suggestion
<script
  data-goatcounter="https://{{ site.goatcounter.id }}.goatcounter.com/count"
  async
  src="https://gc.zgo.at/count.js"
></script>
```

2024-02-06 12:01 UTC, smorkolama commented
Thanks for the PR review, I have applied your suggestions!

2024-02-06 12:05 UTC, cotes2020 requested changes

2024-02-06 12:05 UTC, cotes2020 commented on _includes/goatcounter.html
> +        async src="https://gc.zgo.at/count.js"></script>
Looks like this line is redundant.

```suggestion
```

2024-02-06 14:17 UTC, cotes2020 approved these changes

2024-02-06 14:19 UTC, merged

2024-03-19 13:23 UTC, seaque commented
where exactly can we find GoatCounter id?

2024-03-19 13:31 UTC, smorkolama commented
> where exactly can we find GoatCounter id?

It's the same value as the subdomain you use to access the goatcounter.com site, in case of https://xyz.goatcounter.com it will be `xyz`