Update site title tag from <h1> to <p>
cotes2020/jekyll-theme-chirpy pull request #1960
Opened 2024-09-23 17:01 UTC by kungfux

## Type of change
- [x] Improvement (refactoring and improving code)

## Description
I would like to eliminate the use of `<h1>`for site title in the sidebar. Ref #1907 

## Additional context
I am having problems with search engines indexing blog posts. I would like to make the `<h1>` tag unique for post titles.

2024-09-23 17:33 UTC, cotes2020 requested changes
Hi @kungfux, 

Thanks for fixing it! I think we could just keep the `a` element:

```diff
-    <p class="site-title">
-      <a href="{{ '/' | relative_url }}">{{ site.title }}</a>
-    </p>
+    <a class="site-title d-block" href="{{ '/' | relative_url }}">{{ site.title }}</a>
```

2024-09-23 17:45 UTC, kungfux commented
> Hi @kungfux,
> 
> Thanks for fixing it! I think we could just keep the `a` element:
> 
> ```diff
> -    <p class="site-title">
> -      <a href="{{ '/' | relative_url }}">{{ site.title }}</a>
> -    </p>
> +    <a class="site-title d-block" href="{{ '/' | relative_url }}">{{ site.title }}</a>
> ```

Proposed change will have visual difference as the following on hover rule will not work:

```
#sidebar .sidebar-bottom #mode-toggle:hover, #sidebar .sidebar-bottom a:hover, #sidebar .site-title a:hover {
    color: var(--sidebar-active-color);
}
```

2024-09-23 17:59 UTC, cotes2020 commented
Yes, I overlooked that. But it's easy to recover: just delete line _749_ and _754_ of `_sass/addon/commons.scss`.

https://github.com/cotes2020/jekyll-theme-chirpy/blob/73749067c5e94849bea9cd8146ebe4965f7ed894/_sass/addon/commons.scss#L749-L754

2024-09-23 19:26 UTC, kungfux commented
> Yes, I overlooked that. But it's easy to recover: just delete line _749_ and _754_ of `_sass/addon/commons.scss`.
> 
> https://github.com/cotes2020/jekyll-theme-chirpy/blob/73749067c5e94849bea9cd8146ebe4965f7ed894/_sass/addon/commons.scss#L749-L754

These rules seem necessary. I made changes to preserve the current look and behavior on hover. Please have a look.

2024-09-24 00:12 UTC, cotes2020 commented
> These rules seem necessary.

Of course it is. What I meant earlier was:

```diff
- a { // line 749
      @extend %clickable-transition; 
      @extend %sidebar-link-hover; 
  
      color: var(--site-title-color); 
- } // line 754
```

2024-09-24 00:21 UTC, cotes2020 approved these changes

2024-09-24 00:21 UTC, merged

2024-09-24 06:11 UTC, kungfux commented
> > These rules seem necessary.
> 
> Of course it is. What I meant earlier was:
> 
> ```diff
> - a { // line 749
>       @extend %clickable-transition; 
>       @extend %sidebar-link-hover; 
>   
>       color: var(--site-title-color); 
> - } // line 754
> ```

A coder sits, eyes heavy with sleep,
Writing code in the silence, deep.
Lines of logic begin to blur,
As hidden meanings start to stir.

Between the lines, the messages hide,
But through the yawns, they're hard to guide.
He dreams of rest, but code won't wait,
Another bug to investigate.

With sleepy sighs, mistakes appear,
The code's not quite as crystal clear.
He pushes it, then starts to sway,
And drifts to sleep before the day.