Fixes: Some assets is 404 when baseurl isn't empty and assets is 'self_host'
cotes2020/jekyll-theme-chirpy pull request #590
Opened 2022-06-01 06:57 UTC by LawssssCat

## Description

Fixes: Some assets is 404 when baseurl isn't empty and assets is 'self_host'

```yml
baseurl: /i-am-not-empty
assets:
  self_host: true
    enabled:      # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env:          # [development|production]
```

![image](https://user-images.githubusercontent.com/18041500/171345377-eee6df6b-9381-48e8-ad56-9faf0855ca92.png)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How has this been tested

- [ ] I have run `bash ./tools/deploy.sh --dry-run` (at the root of the project) locally and passed
- [x] I have tested this feature in the browser

### Test Configuration

- Browser type & version: chrome
- Operating system: win10
- Ruby version: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x64-mingw-ucrt] 
- Bundler version: Bundler version 2.3.14 
- Jekyll version:   * jekyll (4.2.2) 

### Checklist

- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [] My changes generate no new warnings

2022-06-01 09:01 UTC, LawssssCat commented
> Thanks for reporting this bug. However, in your patch, cross-domain URLs will also be filtered by `relative_url`, which is not necessary and will affect the readability of the code. So maybe a better way is to handle `baseurl` in `_data/assets/self_host.yml`

It may affect readability, but this `relative_url` is officially provided by liquid, so everyone should be aware of its function, and the liquid seems to have a hunch that `relative_url` will be uesed to filter `cross-domain URLs` so it doesn't seem to do extra processing for `cross-domain URLs`. On the contrary, every time you modify the `baseurl`, you need to modify `_data/assets/self_host.yml` synchronously, which makes me fell very troublesome, so I think `relative_url` should be added.

2022-06-01 09:34 UTC, LawssssCat commented
> Maybe you don't get my point, of course we need `relative_url`, but I mean it should be used in the file `_data/assets/self_host.yml`, not in those HTML files.

Yes， I didn't understand what you were trying to du, because I just tried it and `relative_url` doesn't seem to work in `_data/*`
(Is there any syntax I don't know yet?)

```yml
---
---

# fonts

webfonts: {{ "/assets/lib/fonts/main.css" | relative_url }}
```

2022-06-01 16:53 UTC, cotes2020 commented
Well, I didn't notice that Jekyll doesn't support parsing Liquid filters in data files, so adding baseurl in the HTML file is the only option left, will merge this PR.

2022-06-01 17:00 UTC, cotes2020 requested changes

2022-06-01 17:00 UTC, cotes2020 commented on _includes/js-selector.html
> +    | append: ',' | append: site.data.assets[origin].dayjs.js.localizedFormat
Please undo these indents

2022-06-01 17:02 UTC, cotes2020 requested changes

2022-06-02 08:09 UTC, cotes2020 requested changes
If you can, squash all your commits, then rebase to the latest commit on the master branch.

2022-06-02 09:45 UTC, closed without merging